import { useEffect, useState, type SetStateAction } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import type { RootState, AppDispatch } from '../../store';
import { fetchDispatches } from '../../store/features/sales/dispatchSlice';
import { fetchExpenses } from '../../store/features/expenses/expensesSlice';
import { fetchSellers } from '../../store/features/sellers/sellersSlice';
import { FaDollarSign, FaUserTie, FaChartBar, FaMoneyBillWave, FaDownload } from 'react-icons/fa';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import Button from '../../components/ui/Button';

import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// ----------------- PDF Styles -----------------
export const styles = StyleSheet.create({
  page: { padding: 25, fontSize: 12, fontFamily: 'Helvetica', backgroundColor: '#fff' },
  header: { fontSize: 22, fontWeight: 'bold', textAlign: 'center', marginBottom: 15 },
  subHeader: { fontSize: 14, marginBottom: 5, fontWeight: 'bold' },
  section: { marginBottom: 15 },
  statContainer: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 15 },
  statBox: { flex: 1, padding: 10, marginRight: 10, backgroundColor: '#f3f4f6', borderRadius: 6, textAlign: 'center' },
  statLabel: { fontSize: 10, color: '#4b5563', marginBottom: 5 },
  statValue: { fontSize: 14, fontWeight: 'bold', color: '#111827' },
  tableHeader: { flexDirection: 'row', backgroundColor: '#e5e7eb', borderBottomWidth: 1, borderTopWidth: 1, borderColor: '#9ca3af', paddingVertical: 6, paddingHorizontal: 4, marginBottom: 2 },
  tableRow: { flexDirection: 'row', borderBottomWidth: 0.5, borderColor: '#d1d5db', paddingVertical: 6, paddingHorizontal: 4 },
  tableCell: { flex: 1, textAlign: 'left', fontSize: 10 },
  tableCellCenter: { flex: 1, textAlign: 'center', fontSize: 10 },
  tableCellRight: { flex: 1, textAlign: 'right', fontSize: 10 },
  footer: { marginTop: 20, fontSize: 10, textAlign: 'center', color: '#6b7280' },
});

// ----------------- PDF Component -----------------
export const PDFReport = ({ stats = [], sellersData = [], rangeType = 'day', filterDate = new Date() }: any) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>POS Ripoti ya Dispatch na Matumizi</Text>
      <Text style={styles.subHeader}>Kipengele cha Muda: {rangeType}</Text>
      <Text style={styles.subHeader}>Tarehe: {filterDate ? filterDate.toLocaleDateString() : 'All'}</Text>

      {/* Stats Boxes */}
      <View style={styles.statContainer}>
        {stats.map((stat: any, i: number) => (
          <View key={i} style={styles.statBox}>
            <Text style={styles.statLabel}>{stat.label}</Text>
            <Text style={styles.statValue}>{stat.value}</Text>
          </View>
        ))}
      </View>

      {/* Seller Performance Table */}
      <Text style={styles.subHeader}>Ufanisi wa Muuzaji</Text>
      <View style={styles.tableHeader}>
        <Text style={styles.tableCell}>Jina la Muuzaji</Text>
        <Text style={styles.tableCellCenter}>Idadi ya Mauzo</Text>
        <Text style={styles.tableCellRight}>Jumla ya Mapato (TSh)</Text>
      </View>
      {sellersData.map((s: any, i: number) => (
        <View key={i} style={styles.tableRow}>
          <Text style={styles.tableCell}>{s.sellerName}</Text>
          <Text style={styles.tableCellCenter}>{s.totalSales}</Text>
          <Text style={styles.tableCellRight}>{s.totalRevenue.toLocaleString()}</Text>
        </View>
      ))}

      <Text style={styles.footer}>Generated by POS System</Text>
    </Page>
  </Document>
);

// ----------------- Main Component -----------------
export default function Report() {
  const dispatch = useDispatch<AppDispatch>();

  const { records: dispatchRecordsRaw, loading: dispatchLoading } = useSelector((state: RootState) => state.dispatch);
  const { expenses: expensesRaw, loading: expensesLoading } = useSelector((state: RootState) => state.expenses);
  const { sellers, loading: sellersLoading } = useSelector((state: RootState) => state.sellers);

  const [rangeType, setRangeType] = useState<'day' | 'week' | 'month' | 'year'>('day');
  const [filterDate, setFilterDate] = useState<Date | null>(new Date());
  const loading = dispatchLoading || expensesLoading || sellersLoading;

  if(!loading) return <div>Loading</div>;

  // ----------------- Normalize Timestamps -----------------
const dispatchRecords = dispatchRecordsRaw.map(d => ({
  ...d,
  date: new Date(d.date),
}));

  const expenses = expensesRaw.map(e => ({
    ...e,
    date: e.date instanceof Date ? e.date : e.date?.toDate ? e.date.toDate() : new Date(e.date),
  }));

  useEffect(() => {
    dispatch(fetchDispatches());
    dispatch(fetchExpenses());
    dispatch(fetchSellers());
  }, [dispatch]);

  // ----------------- Filter Function -----------------
  const filterByRange = <T extends { date: Date }>(items: T[]): T[] => {
    if (!filterDate) return items;
    return items.filter(item => {
      const itemDate = item.date instanceof Date ? item.date : new Date(item.date);

      switch (rangeType) {
        case 'day':
          return itemDate.toDateString() === filterDate.toDateString();

        case 'week': {
          const weekStart = new Date(filterDate);
          weekStart.setDate(filterDate.getDate() - filterDate.getDay());
          weekStart.setHours(0, 0, 0, 0);

          const weekEnd = new Date(weekStart);
          weekEnd.setDate(weekStart.getDate() + 6);
          weekEnd.setHours(23, 59, 59, 999);

          return itemDate >= weekStart && itemDate <= weekEnd;
        }

        case 'month':
          return itemDate.getFullYear() === filterDate.getFullYear() &&
                 itemDate.getMonth() === filterDate.getMonth();

        case 'year':
          return itemDate.getFullYear() === filterDate.getFullYear();

        default:
          return true;
      }
    });
  };

  const filteredDispatches = filterByRange(dispatchRecords);
  const filteredExpenses = filterByRange(expenses);

  // ----------------- Stats -----------------
  const totalRevenue = filteredDispatches.reduce((sum, r) => sum + r.cashCollected, 0);
  const totalExpenses = filteredExpenses.reduce((sum, e) => sum + e.amount, 0);
  const netProfit = totalRevenue - totalExpenses;

  const sellerMap: Record<string, { totalRevenue: number; totalSales: number }> = {};
  filteredDispatches.forEach(r => {
    if (!sellerMap[r.sellerId]) sellerMap[r.sellerId] = { totalRevenue: 0, totalSales: 0 };
    sellerMap[r.sellerId].totalRevenue += r.cashCollected;
    sellerMap[r.sellerId].totalSales += 1;
  });

  const sellersData = Object.entries(sellerMap)
    .map(([sellerId, data]) => {
      const seller = sellers.find(s => s.id === sellerId);
      return {
        sellerId,
        sellerName: seller ? seller.name : sellerId,
        totalRevenue: data.totalRevenue,
        totalSales: data.totalSales,
      };
    })
    .sort((a, b) => b.totalRevenue - a.totalRevenue);

  const bestSeller = sellersData[0];

  const stats = [
    { label: 'Jumla ya Mapato', value: `TSh ${totalRevenue.toLocaleString()}`, icon: <FaDollarSign /> },
    { label: 'Jumla ya Matumizi', value: `TSh ${totalExpenses.toLocaleString()}`, icon: <FaMoneyBillWave /> },
    { label: 'Faida Halisi', value: `TSh ${netProfit.toLocaleString()}`, icon: <FaChartBar /> },
    { label: 'Muuzaji Bora', value: bestSeller?.sellerName || '—', icon: <FaUserTie /> },
  ];

  // if (loading) return <div className="p-6 text-center text-gray-600">Inapakia ripoti...</div>;

  // ----------------- JSX -----------------
  return (
    <div className="p-4 md:p-6 bg-gray-50 min-h-screen space-y-6 overflow-x-hidden">
      <h3 className="text-2xl md:text-3xl font-bold text-primary">Ripoti ya Mapato na Matumizi</h3>

      {/* Filters */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3 mb-4">
        <label className="font-medium text-gray-700">Chagua Kipengele cha Muda:</label>
        <select value={rangeType} onChange={e => setRangeType(e.target.value as any)} className="border p-2 rounded">
          <option value="day">Siku</option>
          <option value="week">Wiki</option>
          <option value="month">Mwezi</option>
          <option value="year">Mwaka</option>
        </select>

        <DatePicker
          selected={filterDate}
          onChange={(date: SetStateAction<Date | null>) => setFilterDate(date)}
          dateFormat="dd/MM/yyyy"
          isClearable
          placeholderText="Chagua tarehe"
          className="border p-2 rounded w-full sm:w-auto"
        />

        <PDFDownloadLink
          document={<PDFReport stats={stats} sellersData={sellersData} rangeType={rangeType} filterDate={filterDate || new Date()} />}
          fileName={`ripoti_${rangeType}_${filterDate ? filterDate.toLocaleDateString() : 'all'}.pdf`}
        >
          {({ loading }) => (
            <Button className="flex items-center gap-2 mt-2 sm:mt-0">
              <FaDownload /> {loading ? 'Inapakia...' : 'Pakua PDF'}
            </Button>
          )}
        </PDFDownloadLink>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((stat, i) => (
          <div key={i} className="bg-gray-100 p-6 rounded-xl shadow flex items-center space-x-4 border border-gray-100">
            <div className="p-3 rounded-lg text-white text-3xl" style={{ backgroundColor: '#20B2AA' }}>{stat.icon}</div>
            <div>
              <p className="text-sm text-gray-600 font-medium truncate">{stat.label}</p>
              <p className="text-xl font-bold text-gray-800 truncate">{stat.value}</p>
            </div>
          </div>
        ))}
      </div>

      {/* Seller Table */}
      <div className="bg-white rounded-xl shadow border border-gray-100 overflow-hidden">
        <div className="p-4 border-b border-gray-100">
          <h4 className="font-bold text-gray-700">Ufanisi wa Muuzaji</h4>
        </div>

        <div className="hidden md:block overflow-x-auto">
          <table className="w-full text-left min-w-full">
            <thead className="bg-gray-50 text-gray-600 text-sm uppercase">
              <tr>
                <th className="p-4">Jina la Muuzaji</th>
                <th className="p-4 text-center">Idadi ya Mauzo</th>
                <th className="p-4 text-center">Jumla ya Mapato (TSh)</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {sellersData.length === 0 ? (
                <tr>
                  <td colSpan={3} className="p-6 text-center text-gray-500">Hakuna data kwa kipindi hiki.</td>
                </tr>
              ) : (
                sellersData.map(s => (
                  <tr key={s.sellerId} className="hover:bg-gray-50 transition-colors">
                    <td className="p-4 font-medium truncate sm:text-sm">{s.sellerName}</td>
                    <td className="p-4 text-center">{s.totalSales}</td>
                    <td className="p-4 font-semibold text-green-600 text-right">TSh {s.totalRevenue.toLocaleString()}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <div className="md:hidden space-y-3 p-4">
          {sellersData.length === 0 ? (
            <div className="text-center text-gray-400 italic">Hakuna data kwa kipindi hiki.</div>
          ) : (
            sellersData.map(s => (
              <div key={s.sellerId} className="bg-gray-50 p-4 rounded-lg shadow flex flex-col gap-2">
                <div className="font-medium text-gray-800 truncate">{s.sellerName}</div>
                <div className="flex justify-between text-sm text-gray-600">
                  <span>Mauzo: {s.totalSales}</span>
                  <span className="font-semibold text-green-600">TSh {s.totalRevenue.toLocaleString()}</span>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
